### PR TITLE
Remove QRL

### PR DESCRIPTION
**Pull request by cyyber**
QRL has an automatic checkpointing, which doesnt allow reorg beyond a limit.

### CODE REVIEW

**Comment by tdickman** [comment]
@cyyber Any chance you can link me to documentation on how this automatic checkpointing works?

**Comment by cyyber** [comment]
@tdickman Here is the reference for the code that doesnt allow fork beyond the reorg limit https://github.com/theQRL/QRL/blob/master/src/qrl/core/ChainManager.py#L483

**Comment by tdickman** [comment]
@cyyber Thank you for liking to the code! It looks like the reorg limit is [22000](https://github.com/theQRL/QRL/blob/master/src/qrl/core/config.py#L220) blocks, and the block time in ~56 seconds. This means that reorgs of less than 22000*56s = ~14 days  are allowed. An attacker could still carry out a 51% attack as long as they published the chain split within 14 days, which would be more than sufficient to carry out the attack.

Please let me know if I am misunderstanding how this value is used.

**Comment by cyyber** [comment]
@tdickman We are going to reduce that value soon. In the mean time can you update the hashrate. Current hashrate is above 30 Mh/s

**Comment by tdickman** [comment]
Hash rate is coming from https://minethecoin.com/coin/quantum-resistant-ledger. It looks like that might be inaccurate, feel free to reach out to minethecoin, or submit a pr that pulls from a more accurate source.

**Comment by tdickman** [comment]
Closing for now -> feel free to submit a pr to fix the hashrate. Happy to help if I can.

**Pull request closed without merging**
